# Generated by Django 3.2.21 on 2023-12-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('time', models.TimeField()),
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_description', models.CharField(max_length=200)),
                ('replay', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
    ]
