# Generated by Django 3.2.21 on 2023-12-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=45)),
                ('resume', models.CharField(max_length=60)),
                ('apply_sts', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('place', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'application',
                'managed': False,
            },
        ),
    ]
