# Generated by Django 3.2.21 on 2023-12-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('replay', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=45)),
                ('enquiry', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'enquiry',
                'managed': False,
            },
        ),
    ]
