# Generated by Django 3.2.21 on 2023-12-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=45)),
                ('service_name', models.CharField(max_length=45)),
                ('service_description', models.CharField(max_length=45)),
                ('contact', models.DecimalField(decimal_places=0, max_digits=10)),
                ('city', models.CharField(max_length=45)),
                ('document', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('profile', models.CharField(max_length=45)),
                ('pin', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
    ]
